[build]
  command = "ng build --configuration production"
  publish = "dist/ingsoftware2/browser"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200